[features]
seeds = false
skip-lint = false
[programs.localnet]
batch_transfer = "FddwD1WwcAN5XfR3bzD9jW1wHs4Bg1jz7YXTMicshzZp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/chou/.config/solana/id.json"

[scripts]
test-contract-1 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/batch-transfer-contract-1.ts"
test-contract-2 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/batch-transfer-contract-1.ts"
test-native = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/native/native.ts" 
test-spl = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/token/token.ts" 


