[features]
seeds = false
skip-lint = false

[programs.localnet]
batch_transfer = "FddwD1WwcAN5XfR3bzD9jW1wHs4Bg1jz7YXTMicshzZp"

[programs.devnet]
batch_transfer = "DwZruo6t3BW4DUtALe2i2E6ewA8b5mH1Lk2TWeyV8ymo"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
